name: first workflow

on:
  workflow_dispatch:

jobs:
  firstjob:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello World
        run: echo "Hello World! This is the first job"

      - name: Checkout Repository
        uses: actions/checkout@v4.2.2

      - name: Greet User
        id: print-to-log
        uses: actions/hello-world-javascript-action@main
        with:
          who-to-greet: ${{ github.actor }}

      - name: Print Greeting Time
        run: echo "The time of the greeting was at: ${{ steps.print-to-log.outputs.time }}"

  secondjob:
    runs-on: ubuntu-latest
    steps:
      - name: Second Job Script
        shell: bash
        run: |
          echo "This is the second job"
          echo "And this is a multi-line script"
